apiVersion: apps/v1
kind: Deployment
metadata:
  name: treetracker-api
  labels:
    app: treetracker-api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: treetracker-api
  template:
    metadata:
      labels:
        app: treetracker-api
    spec:
      containers:
      - name: treetracker-api
        image: greenstand/treetracker-api:VERSION
        ports:
        - containerPort: 80
